(() => {
const careers = {
  care:{name:"Registered nurse",median:97550,growth:6,openings:"180,800",route:"Bachelor’s degree, associate degree, or approved diploma program; state licensure.",strength:"Care, communication, clinical judgment",url:"https://www.bls.gov/ooh/healthcare/registered-nurses.htm",note:"National median annual wage, May 2025; projected employment change, 2025-35."},
  tech:{name:"Software developer",median:135980,growth:10,openings:"106,100",route:"Typically a bachelor’s degree; portfolio and technical practice matter.",strength:"Problem-solving, systems thinking, collaboration",url:"https://www.bls.gov/ooh/computer-and-information-technology/software-developers.htm",note:"National median annual wage, May 2025; projected employment change for software developers, QA analysts and testers, 2025-35."},
  build:{name:"HVAC technician",median:61010,growth:11,openings:"40,600",route:"Typically a postsecondary nondegree award plus on-the-job training; some roles require license or certification.",strength:"Hands-on diagnosis, systems, customer communication",url:"https://www.bls.gov/ooh/installation-maintenance-and-repair/heating-air-conditioning-and-refrigeration-mechanics-and-installers.htm",note:"National median annual wage, May 2025; projected employment change, 2025-35."}
};
let state={housing:0,mobility:0,career:""};
const stage=document.querySelector("#stage"), app=document.querySelector("#app"), intro=document.querySelector("#intro");
const progress=document.querySelector("#progressBar"), progressText=document.querySelector("#progressText");
const money=n=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(n);
function setProgress(n){progress.style.width=(n/3*100)+"%";progressText.textContent=n+" / 3"}
function options(title,sub,key,choices,step){setProgress(step);stage.innerHTML='<div class="demo-step"><div class="demo-step-label">YOUR LIFESTYLE LENS</div><h2>'+title+'</h2><p>'+sub+'</p><div class="choice-grid">'+choices.map(c=>'<button class="choice-card" data-value="'+c.value+'"><span class="choice-icon">'+c.icon+'</span><b>'+c.title+'</b><small>'+c.detail+'</small></button>').join("")+'</div><button class="demo-back" data-back>← Back</button></div>';stage.querySelectorAll("[data-value]").forEach(b=>b.onclick=()=>{state[key]=+b.dataset.value; step===1?mobility():career()});stage.querySelector("[data-back]").onclick=()=> step===1?reset():housing();}
function housing(){options("What kind of home base are you imagining?","There is no right answer. We are making the tradeoffs visible.", "housing",[{value:0,icon:"◌",title:"Keep it light",detail:"More flexibility and lower fixed costs"},{value:14000,icon:"⌂",title:"Build some comfort",detail:"More room, stability and amenities"},{value:28000,icon:"✦",title:"Settle in",detail:"A higher-cost home base and lifestyle"}],1)}
function mobility(){options("How much mobility belongs in the picture?","Choose the level that feels closest to your current thinking.", "mobility",[{value:0,icon:"↗",title:"Keep it local",detail:"Simple transportation and occasional trips"},{value:7000,icon:"◎",title:"Room to move",detail:"Reliable vehicle and regular travel"},{value:14000,icon:"✈",title:"Freedom to explore",detail:"Higher transportation and travel priorities"}],2)}
function career(){setProgress(3); stage.innerHTML='<div class="demo-step"><div class="demo-step-label">CAREER DIRECTION</div><h2>Which kind of work pulls you in?</h2><p>Select the work pattern that feels most worth investigating. This does not lock you into a result.</p><div class="choice-grid career-choices"><button class="choice-card" data-career="care"><span class="choice-icon">♡</span><b>Help people directly</b><small>Care, communication and applied clinical work</small></button><button class="choice-card" data-career="tech"><span class="choice-icon">⌘</span><b>Build with technology</b><small>Problem-solving, systems and digital products</small></button><button class="choice-card" data-career="build"><span class="choice-icon">⚙</span><b>Fix what keeps life running</b><small>Hands-on systems work and visible results</small></button></div><button class="demo-back" data-back>← Back</button></div>';stage.querySelectorAll("[data-career]").forEach(b=>b.onclick=()=>{state.career=b.dataset.career;results()});stage.querySelector("[data-back]").onclick=mobility}
function results(){const c=careers[state.career], target=48000+state.housing+state.mobility, gap=c.median-target;setProgress(3);stage.innerHTML='<div class="demo-results"><div class="results-eyebrow">YOUR PREVIEW PATH</div><div class="result-hero"><div><h2>A life target gives a career question real weight.</h2><p>Your <b>illustrative</b> income lens is <strong>'+money(target)+'</strong> per year.</p><small>Preview formula: a $48,000 baseline plus the lifestyle choices you selected. It is a conversation prompt - not your actual Career Navideer Lifestyle Index.</small></div><div class="fit-meter"><span>MEDIAN WAGE LENS</span><b>'+money(c.median)+'</b><i><em style="width:'+Math.min(100,Math.max(20,c.median/target*72))+'%"></em></i><small>'+(gap>=0?money(gap)+" above":" "+money(Math.abs(gap))+" below")+' this illustrative target</small></div></div><div class="career-data"><div class="career-name"><div class="career-badge">'+(state.career==="care"?"♡":state.career==="tech"?"⌘":"⚙")+'</div><div><span>REAL OCCUPATION SNAPSHOT</span><h3>'+c.name+'</h3><p>'+c.strength+'</p></div><a href="'+c.url+'" target="_blank" rel="noopener">View BLS source ↗</a></div><div class="data-row"><article><span>U.S. MEDIAN PAY</span><b>'+money(c.median)+'</b><small>May 2025</small></article><article><span>PROJECTED GROWTH</span><b>+'+c.growth+'%</b><small>2025-2035</small></article><article><span>ANNUAL OPENINGS</span><b>'+c.openings+'</b><small>projected average</small></article></div><div class="route-card"><span>PREPARATION LENS</span><p>'+c.route+'</p><small>'+c.note+' Source: U.S. Bureau of Labor Statistics, Occupational Outlook Handbook.</small></div></div><div class="next-conversation"><div><span>WHAT CAREER NAVIDEER ADDS</span><h3>Do not stop at the wage.</h3><p>In the full platform, this is where a learner can investigate tasks, skills, values, education routes and an ongoing Career Path - not just compare one number.</p></div><div class="result-actions"><a class="demo-live" href="https://app.careernavideer.com/">Explore Career Navideer <b>→</b></a><a href="request-demo.html">Request a guided demo</a></div></div><button class="demo-restart" data-restart>↻ Try another path</button></div>';stage.querySelector("[data-restart]").onclick=reset}
function reset(){state={housing:0,mobility:0,career:""};housing()}
document.querySelector("[data-start]").onclick=()=>{intro.hidden=true;app.hidden=false;housing();window.scrollTo({top:0,behavior:"smooth"})};
})();