const menu=document.querySelector('.menu');
const links=document.querySelector('.navlinks');
if(!document.querySelector('link[href="enhancements.css"]')){const enhancements=document.createElement('link');enhancements.rel='stylesheet';enhancements.href='enhancements.css';document.head.append(enhancements)}
if(links){const page=location.pathname.split('/').pop()||'index.html';for(const link of links.querySelectorAll('a')){const href=(link.getAttribute('href')||'').split('?')[0];if(href===page)link.classList.add('current-page')}}
if(links&&!links.querySelector('a[href="blog.html"]')){const insight=document.createElement('a');insight.href='blog.html';insight.textContent='Insights';const pricing=links.querySelector('a[href="pricing.html"]');if(pricing)links.insertBefore(insight,pricing);else links.append(insight)}
if(links&&!links.querySelector('.signup-link')){
  if(!links.querySelector('a[href="index.html"]')){const home=document.createElement('a');home.href='index.html';home.textContent='Home';home.className='mobile-home-link';links.prepend(home)}
  const signup=document.createElement('a');signup.href='https://app.careernavideer.com/';signup.textContent='Sign Up';signup.className='signup-link';
  const institutional=links.querySelector('.btn.primary');if(institutional)links.insertBefore(signup,institutional);else links.append(signup);
}
if(menu&&links){menu.setAttribute('aria-expanded','false');menu.addEventListener('click',()=>{const open=links.dataset.open==='1';links.dataset.open=open?'0':'1';menu.setAttribute('aria-expanded',open?'false':'true');menu.setAttribute('aria-label',open?'Open menu':'Close menu');if(open){links.removeAttribute('style')}else{Object.assign(links.style,{display:'flex',position:'absolute',top:'68px',left:'0',right:'0',background:'#fff',padding:'22px',flexDirection:'column',borderBottom:'1px solid #d9e5ec',boxShadow:'0 16px 30px rgba(7,29,51,.12)'})}});document.addEventListener('keydown',event=>{if(event.key==='Escape'&&links.dataset.open==='1'){links.dataset.open='0';links.removeAttribute('style');menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','Open menu');menu.focus()}})}
for(const f of document.querySelectorAll('form[data-demo]')){f.addEventListener('submit',e=>{e.preventDefault();const msg=f.querySelector('.formmsg');if(msg)msg.textContent='Development preview: form routing will be connected before production launch.'})}

const reportContent={
  summary:'<div class="report-stat"><span>MEDIAN WAGE</span><b>$101,020</b><small>National figure shown in the platform report</small></div><div class="report-stat"><span>PROJECTED GROWTH</span><b>15.1%</b><small>2020-2030 report period</small></div><div class="report-detail-card"><span>EDUCATION</span><h3>Extensive preparation</h3><p>Compare reported education levels, areas of study, programs and credentials before committing.</p></div><div class="report-detail-card"><span>DECISION LENS</span><h3>More than salary</h3><p>Explore tasks, tools, interests, work styles, values, related occupations and certifications.</p></div>',
  kas:'<div class="report-detail-card"><span>SKILL • TARGET LEVEL 59</span><h3>Active Listening</h3><p>Examples progress from taking a customer order, to interviewing an applicant, to understanding a complex professional case.</p></div><div class="report-detail-card"><span>ABILITY • TARGET LEVEL 61</span><h3>Oral Comprehension</h3><p>Compare the occupation level with the learner\'s own rating and supporting experience.</p></div><div class="report-detail-card"><span>KNOWLEDGE • TARGET LEVEL 74</span><h3>Therapy and Counseling</h3><p>Make the development gap visible, specific and actionable.</p></div><div class="report-detail-card"><span>SELF-ASSESSMENT</span><h3>From requirement to plan</h3><p>Select relevant KAS, rate current capability and choose what to strengthen next.</p></div>',
  context:'<div class="report-stat"><span>CONTACT WITH OTHERS</span><b>94%</b><small>responded constant contact with others</small></div><div class="report-stat"><span>PHYSICAL PROXIMITY</span><b>93%</b><small>responded very close or near touching</small></div><div class="report-detail-card"><span>DECISION-MAKING</span><h3>Freedom and responsibility</h3><p>Investigate decision frequency, consequences of error and impact on others.</p></div><div class="report-detail-card"><span>WORK VALUES</span><h3>Relationships and achievement</h3><p>Ask whether service, accomplishment, recognition, independence and support fit.</p></div>',
  path:'<div class="report-detail-card"><span>SKILLS DEVELOPMENT</span><h3>Practice with purpose</h3><p>Choose activities, timeframes and evidence of progress.</p></div><div class="report-detail-card"><span>ABILITY & KNOWLEDGE</span><h3>Build readiness</h3><p>Track capacity and knowledge acquisition for each selected occupation.</p></div><div class="report-detail-card"><span>WHO HELPS</span><h3>Network and mentors</h3><p>Add advisors, connectors and professionals who can inform the journey.</p></div><div class="report-detail-card"><span>SUSTAIN THE JOURNEY</span><h3>Self-care and return</h3><p>Save progress, protect wellbeing and return as experience changes the plan.</p></div>'
};
for(const button of document.querySelectorAll('[data-report-tab]')){button.addEventListener('click',()=>{document.querySelectorAll('[data-report-tab]').forEach(b=>b.classList.remove('active'));button.classList.add('active');const panel=document.querySelector('[data-report-panel]');if(panel)panel.innerHTML=reportContent[button.dataset.reportTab]})}
const saveSession=document.querySelector('[data-save-session]');if(saveSession)saveSession.addEventListener('click',()=>{saveSession.classList.toggle('saved');saveSession.textContent=saveSession.classList.contains('saved')?'Session saved - return anytime':'Save this session'});
for(const button of document.querySelectorAll('[data-value-tab]')){button.setAttribute('aria-selected',button.classList.contains('active'));button.addEventListener('click',()=>{document.querySelectorAll('[data-value-tab]').forEach(b=>{b.classList.toggle('active',b===button);b.setAttribute('aria-selected',b===button)});document.querySelectorAll('[data-value-panel]').forEach(p=>p.hidden=p.dataset.valuePanel!==button.dataset.valueTab)})}
